name: CI

on: [pull_request]

jobs:
  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.12.1]
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Linters
        run: yarn lint
      - name: Tests
        run: yarn test:ci
      - name: Build
        run: yarn build
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
        - 3.1.2
        database-name:
        - backend
        database-password:
        - postgres
        database-user:
        - postgres
        database-host:
        - 127.0.0.1
        database-port:
        - 5432
    defaults:
      run:
        working-directory: ./backend
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ matrix.database-name }}
          POSTGRES_USER: ${{ matrix.database-user }}
          POSTGRES_PASSWORD: ${{ matrix.database-password }}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Setup system dependencies
        run: sudo apt-get install libpq-dev
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install
      - name: Linters
        run: rubocop
      - name: Tests
        env:
          RAILS_ENV: test
          DATABASE_NAME_TEST: ${{ matrix.database-name }}
          DATABASE_USER: ${{ matrix.database-user }}
          DATABASE_PASSWORD: ${{ matrix.database-password }}
          DATABASE_HOST: ${{ matrix.database-host }}
          DATABASE_PORT: ${{ matrix.database-port }}
          POSTGRES_DB: ${{ matrix.database-name }}
        run: |
          rails db:create
          rails db:migrate
          rspec
